language: java

jdk:
  - oraclejdk8

before_install:
  - chmod +x gradlew

script: ./gradlew check

addons:
  apt:
    sources:
      - sourceline: 'ppa:mosquitto-dev/mosquitto-ppa'
    packages:
      - mosquitto
