language: java

jdk:
  - oraclejdk8

script: ./gradlew check

cache:
  apt: true
  directories:
    - $HOME/.gradle/caches
    - $HOME/.gradle/wrapper

addons:
  apt:
    sources:
      - sourceline: 'ppa:mosquitto-dev/mosquitto-ppa'
    packages:
      - mosquitto
